name: Contrast Security SCA
on:
  pull_request:
    branches:
      - "main"
jobs:
  Check-Dependency-Vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: build jar
        run: |
          mvn clean install -DskipTests
      - name: Contrast SCA Action
        uses: Contrast-Security-OSS/contrast-sca-action@v2
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          filePath: pom.xml
          severity: medium
          outputSummary: true
          fail: true
